name = "lapce-lsp-xml"
version = "0.0.1"
author = "xiaoma20082008"
display-name = "xml"
description = "Xml for Lapce: powered by Lemminx"
wasm = "bin/lapce-lsp-xml.wasm"
repository = "https://github.com/xiaoma20082008/lapce-lsp-xml.git"

[activation]
language = ["xml"]
workspace-contains = [
    "*/*.xml"
]

[config."lapce-lsp-xml.serverPath"]
default = ""
description = "Path to XML LSP executable"

[config."lapce-lsp-xml.serverArgs"]
default = []
description = "XML LSP's arguments"

[config."lapce-lsp-xml.lemminx.version"]
default = ""
description = "lemminx-uber's version"

[config."lapce-lsp-xml.lemminx.port"]
default = 5008
description = "lemminx-uber's connection port"

[config."lapce-lsp-xml.lemminx.args"]
default = ""
description = "lemminx-uber's JVM arguments. Like -Xms=32M -Xmx=32M"

